services:
  api:
    build: .
    container_name: document-intelligence-api
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    ports:
      - "8000:8000"

  streamlit:
    build: .
    container_name: document-intelligence-streamlit
    command:
      - streamlit
      - run
      - app/streamlit_app.py
      - --server.address=0.0.0.0
      - --server.port=8501
    environment:
      API_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api